### ISSUE TITLE
ort::Session 没有成员GetOutputName

### ISSUE THREAD

**Issue by XilinGong** [hpc203/pp-yoloe-hrnet-human_pose_estimation#2]
windows下直接用vs配置，尝试了1.8.1和1.13.1版本。均有main.cpp报错ort::Session 没有成员GetOutputName，ort::Session 没有成员GetInputName。请问是什么原因呀？和版本问题有关吗

**Comment by Songxinlei** [comment]
已经弃用了，换成getOutputNameAllocated()了
